service: url-generator
frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-jest-plugin
custom:
  jest:
    collectCoverage: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  new-url:
    handler: handlers/new-url/index.handler
  # hello:
  #   handler: handler.handler
    events:
      - http:
          path: /
          method: post
