service: url-generator
frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-jest-plugin
custom:
  jest:
    collectCoverage: true

provider:
  name: aws
  region: eu-west-2
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:*"


functions:
  new-url:
    handler: handlers/new-url/index.handler
    events:
      - http:
          path: /
          method: post

  get-urls:
    handler: handlers/get-urls/index.handler
    events:
      - http:
          path: /
          method: get

resources:
  Resources:
    IAmArlaDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: newUrl
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

        GlobalSecondaryIndexes:

          - IndexName: newUrlIndex
            KeySchema:
              - AttributeName: newUrl
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

        TableName: ${self:provider.environment.DYNAMODB_TABLE}
